Read me game instructions
taiwocoker/Tic-Tac-Toe pull request #5
Opened 2020-05-25 10:34 UTC by imhilla

In this milestone, we had the chance to explain the TicTacToe game.
The first section introduces how the game is played
The second section explains the game rules.
The lower section explains how to set up locally and play on the command line

2020-05-25 12:11 UTC, whiz25 commented on README.md
> +If the clone was successful, a new sub-directory appears on your local drive in the directory where you cloned your repository. This directory has the same name as the github repository that you clon
- how does someone clone the repo. what command should they type? include technical details
- be precise with the instructions

2020-05-25 12:13 UTC, whiz25 commented on README.md
> +The first player that has a line of three X's or three O's wins the game.
- divide this into two sections. move some content from here to a "Rules section" for the game.

2020-05-25 12:14 UTC, whiz25 commented on README.md
> +Twitter: @SelloCoker
- add a section for contributing

2020-05-25 12:16 UTC, whiz25 requested changes
## Awesome progress :+1: 
Your readme looks good but it's not professional enough. Make the changes I have suggested and make this more professional.

### Martin Afani

2020-05-25 18:54 UTC, pelzolga123 approved these changes
Approved.

2020-05-25 18:55 UTC, pelzolga123 commented
## Great work, congratulation :+1: Project Approved.
You did all changes required previously, but I would still advise a few more changes, to make README file look better:
* Make all headers the same size, except for `Tic-Tac-Toe`, it should be bigger than other headers.
* The header of `contributing` section does not look like header, please kindly change that.

Then go ahead and merge to develop.
_Goodluck in your next project_ *Happy coding*

2020-05-26 03:36 UTC, imhilla commented
> ## Great work, congratulation 👍 Project Approved.
> You did all changes required previously, but I would still advise a few more changes, to make README file look better:
> 
> * Make all headers the same size, except for `Tic-Tac-Toe`, it should be bigger than other headers.
> * The header of `contributing` section does not look like header, please kindly change that.
> 
> Then go ahead and merge to develop.
> _Goodluck in your next project_ _Happy coding_

noted and changed

2020-05-26 07:57 UTC, merged